name: Ingest Spotify tracks

on:
  workflow_dispatch:
    inputs:
      playlists:
        description: 'Comma-separated playlist ids (e.g. 37i9dQZF1DXcBWIGoYBM5M)'
        required: false
        default: ''
      artists:
        description: 'Comma-separated artist names (e.g. Adele,Coldplay)'
        required: false
        default: ''
      max_tracks:
        description: 'Max tracks to fetch'
        required: false
        default: '1000'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r projects/01_EDA_Canciones/requirements.txt

      - name: Create .env from secrets
        run: |
          cat > .env <<EOF
          SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}
          MAX_TRACKS=${{ secrets.MAX_TRACKS }}
          EOF

      - name: Run ingest script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        run: |
          mkdir -p projects/01_EDA_Canciones/src/data
          python projects/01_EDA_Canciones/src/scripts/ingest_spotify.py \
            --playlists "${{ github.event.inputs.playlists }}" \
            --artists "${{ github.event.inputs.artists }}" \
            --out projects/01_EDA_Canciones/src/data/spotify_tracks.csv \
            --max_tracks ${{ github.event.inputs.max_tracks }}

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify_tracks_csv
          path: projects/01_EDA_Canciones/src/data/spotify_tracks.csv
